M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Mon 11 Sep 2023 19:10:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-11T19:10:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X29.6Y-0.95
X29.6Y-5.15
X33.0Y-0.95
X33.0Y-5.15
T0
M30
